name       : spotify-qt
version    : '3.10'
release    : 4
source     :
    - https://github.com/kraxarn/spotify-qt/archive/refs/tags/v3.10.tar.gz : 66191fc75f8571f40be16582caded2e6e3181434cbab5e85d3e9613c97ecb44f
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Lightweight Spotify client using Qt
description: |
    Spotify client using Qt as a simpler, lighter alternative to the official client, inspired by spotify-tui.
builddeps  :
    - pkgconfig(Qt5Svg)
rundeps    :
    - qt5-svg
    - spotifyd
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
