name       : spotify-qt
version    : 3.7
release    : 1
source     :
    - https://github.com/kraxarn/spotify-qt/archive/v3.5.tar.gz : b8c4827a6c3e012b897f0a87ef2cc6e04b2d97f14bc505d19ebd439464094b4e
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Lightweight Spotify client using Qt
description: |
    Spotify client using Qt as a simpler, lighter alternative to the official client, inspired by spotify-tui.
builddeps  :
    - pkgconfig(Qt5Svg)
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
